// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ReservationStatus string

const (
	ReservationStatusConfirmed ReservationStatus = "confirmed"
	ReservationStatusCancelled ReservationStatus = "cancelled"
	ReservationStatusCheckedIn ReservationStatus = "checked_in"
	ReservationStatusNoShow    ReservationStatus = "no_show"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type ResourceType string

const (
	ResourceTypeRoom      ResourceType = "room"
	ResourceTypeDesk      ResourceType = "desk"
	ResourceTypeParking   ResourceType = "parking"
	ResourceTypeEquipment ResourceType = "equipment"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType `json:"resource_type"`
	Valid        bool         `json:"valid"` // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type SsoProtocol string

const (
	SsoProtocolSaml   SsoProtocol = "saml"
	SsoProtocolOidc   SsoProtocol = "oidc"
	SsoProtocolOauth2 SsoProtocol = "oauth2"
)

func (e *SsoProtocol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SsoProtocol(s)
	case string:
		*e = SsoProtocol(s)
	default:
		return fmt.Errorf("unsupported scan type for SsoProtocol: %T", src)
	}
	return nil
}

type NullSsoProtocol struct {
	SsoProtocol SsoProtocol `json:"sso_protocol"`
	Valid       bool        `json:"valid"` // Valid is true if SsoProtocol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSsoProtocol) Scan(value interface{}) error {
	if value == nil {
		ns.SsoProtocol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SsoProtocol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSsoProtocol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SsoProtocol), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleMember  UserRole = "member"
	UserRoleGuest   UserRole = "guest"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Reservation struct {
	ID         pgtype.UUID                      `json:"id"`
	TenantID   pgtype.UUID                      `json:"tenant_id"`
	UserID     pgtype.UUID                      `json:"user_id"`
	ResourceID pgtype.UUID                      `json:"resource_id"`
	During     pgtype.Range[pgtype.Timestamptz] `json:"during"`
	Status     ReservationStatus                `json:"status"`
	Notes      pgtype.Text                      `json:"notes"`
	CreatedAt  pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz               `json:"updated_at"`
}

type Resource struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Type      ResourceType       `json:"type"`
	Capacity  int32              `json:"capacity"`
	Floor     pgtype.Int4        `json:"floor"`
	Amenities []string           `json:"amenities"`
	IsActive  bool               `json:"is_active"`
	Location  interface{}        `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SsoProvider struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Protocol  SsoProtocol        `json:"protocol"`
	IssuerUrl string             `json:"issuer_url"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	SsoEnforced bool               `json:"sso_enforced"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      UserRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserIdentity struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Subject    string             `json:"subject"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
