// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateSsoProvider(ctx context.Context, arg CreateSsoProviderParams) (SsoProvider, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteReservation(ctx context.Context, id pgtype.UUID) error
	DeleteResource(ctx context.Context, id pgtype.UUID) error
	DeleteSsoProvider(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error)
	GetResource(ctx context.Context, id pgtype.UUID) (Resource, error)
	GetSsoProvider(ctx context.Context, id pgtype.UUID) (SsoProvider, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error)
	ListReservationsByResource(ctx context.Context, arg ListReservationsByResourceParams) ([]Reservation, error)
	ListReservationsByTimeRange(ctx context.Context, arg ListReservationsByTimeRangeParams) ([]Reservation, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]Reservation, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	ListResourcesAvailable(ctx context.Context, arg ListResourcesAvailableParams) ([]Resource, error)
	ListResourcesByFloor(ctx context.Context, arg ListResourcesByFloorParams) ([]Resource, error)
	ListResourcesByType(ctx context.Context, arg ListResourcesByTypeParams) ([]Resource, error)
	ListSsoProviders(ctx context.Context, arg ListSsoProvidersParams) ([]SsoProvider, error)
	ListSsoProvidersActive(ctx context.Context, arg ListSsoProvidersActiveParams) ([]SsoProvider, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
