// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (tenant_id, user_id, resource_id, during, status, notes) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at
`

type CreateReservationParams struct {
	TenantID   pgtype.UUID                      `json:"tenant_id"`
	UserID     pgtype.UUID                      `json:"user_id"`
	ResourceID pgtype.UUID                      `json:"resource_id"`
	During     pgtype.Range[pgtype.Timestamptz] `json:"during"`
	Status     ReservationStatus                `json:"status"`
	Notes      pgtype.Text                      `json:"notes"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.TenantID,
		arg.UserID,
		arg.ResourceID,
		arg.During,
		arg.Status,
		arg.Notes,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ResourceID,
		&i.During,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (tenant_id, name, type, capacity, floor, amenities, location) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, tenant_id, name, type, capacity, floor, amenities, is_active, location, created_at
`

type CreateResourceParams struct {
	TenantID  pgtype.UUID  `json:"tenant_id"`
	Name      string       `json:"name"`
	Type      ResourceType `json:"type"`
	Capacity  int32        `json:"capacity"`
	Floor     pgtype.Int4  `json:"floor"`
	Amenities []string     `json:"amenities"`
	Location  interface{}  `json:"location"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Capacity,
		arg.Floor,
		arg.Amenities,
		arg.Location,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Capacity,
		&i.Floor,
		&i.Amenities,
		&i.IsActive,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const createSsoProvider = `-- name: CreateSsoProvider :one
INSERT INTO sso_providers (tenant_id, name, protocol, issuer_url, is_active) VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, name, protocol, issuer_url, is_active, created_at
`

type CreateSsoProviderParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	Protocol  SsoProtocol `json:"protocol"`
	IssuerUrl string      `json:"issuer_url"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) CreateSsoProvider(ctx context.Context, arg CreateSsoProviderParams) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, createSsoProvider,
		arg.TenantID,
		arg.Name,
		arg.Protocol,
		arg.IssuerUrl,
		arg.IsActive,
	)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Protocol,
		&i.IssuerUrl,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, name, role) VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, email, name, role, created_at
`

type CreateUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
	Name     string      `json:"name"`
	Role     UserRole    `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations WHERE id = $1
`

func (q *Queries) DeleteReservation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservation, id)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const deleteSsoProvider = `-- name: DeleteSsoProvider :exec
DELETE FROM sso_providers WHERE id = $1
`

func (q *Queries) DeleteSsoProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSsoProvider, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getReservation = `-- name: GetReservation :one
SELECT id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at FROM reservations WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ResourceID,
		&i.During,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT id, tenant_id, name, type, capacity, floor, amenities, is_active, location, created_at FROM resources WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id pgtype.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Capacity,
		&i.Floor,
		&i.Amenities,
		&i.IsActive,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getSsoProvider = `-- name: GetSsoProvider :one
SELECT id, tenant_id, name, protocol, issuer_url, is_active, created_at FROM sso_providers WHERE id = $1
`

func (q *Queries) GetSsoProvider(ctx context.Context, id pgtype.UUID) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, getSsoProvider, id)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Protocol,
		&i.IssuerUrl,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, sso_enforced, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SsoEnforced,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, email, name, role, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, name, role, created_at FROM users WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listReservations = `-- name: ListReservations :many
SELECT id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at FROM reservations WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReservationsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ResourceID,
			&i.During,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByResource = `-- name: ListReservationsByResource :many
SELECT id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at FROM reservations WHERE resource_id = $1 ORDER BY during DESC LIMIT $2 OFFSET $3
`

type ListReservationsByResourceParams struct {
	ResourceID pgtype.UUID `json:"resource_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListReservationsByResource(ctx context.Context, arg ListReservationsByResourceParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByResource, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ResourceID,
			&i.During,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByTimeRange = `-- name: ListReservationsByTimeRange :many
SELECT id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at FROM reservations WHERE tenant_id = $1 AND during && $2 ORDER BY during LIMIT $3 OFFSET $4
`

type ListReservationsByTimeRangeParams struct {
	TenantID pgtype.UUID                      `json:"tenant_id"`
	During   pgtype.Range[pgtype.Timestamptz] `json:"during"`
	Limit    int32                            `json:"limit"`
	Offset   int32                            `json:"offset"`
}

func (q *Queries) ListReservationsByTimeRange(ctx context.Context, arg ListReservationsByTimeRangeParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByTimeRange,
		arg.TenantID,
		arg.During,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ResourceID,
			&i.During,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUser = `-- name: ListReservationsByUser :many
SELECT id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at FROM reservations WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReservationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ResourceID,
			&i.During,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, tenant_id, name, type, capacity, floor, amenities, is_active, location, created_at FROM resources WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListResourcesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Capacity,
			&i.Floor,
			&i.Amenities,
			&i.IsActive,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesAvailable = `-- name: ListResourcesAvailable :many
SELECT r.id, r.tenant_id, r.name, r.type, r.capacity, r.floor, r.amenities, r.is_active, r.location, r.created_at FROM resources r WHERE r.tenant_id = $1 AND r.is_active = TRUE AND NOT EXISTS (SELECT 1 FROM reservations res WHERE res.resource_id = r.id AND res.during @> $2::timestamptz AND res.status IN ('confirmed', 'checked_in')) ORDER BY r.name LIMIT $3 OFFSET $4
`

type ListResourcesAvailableParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Column2  pgtype.Timestamptz `json:"column_2"`
	Limit    int32              `json:"limit"`
	Offset   int32              `json:"offset"`
}

func (q *Queries) ListResourcesAvailable(ctx context.Context, arg ListResourcesAvailableParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesAvailable,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Capacity,
			&i.Floor,
			&i.Amenities,
			&i.IsActive,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByFloor = `-- name: ListResourcesByFloor :many
SELECT id, tenant_id, name, type, capacity, floor, amenities, is_active, location, created_at FROM resources WHERE tenant_id = $1 AND floor = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListResourcesByFloorParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Floor    pgtype.Int4 `json:"floor"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListResourcesByFloor(ctx context.Context, arg ListResourcesByFloorParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByFloor,
		arg.TenantID,
		arg.Floor,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Capacity,
			&i.Floor,
			&i.Amenities,
			&i.IsActive,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByType = `-- name: ListResourcesByType :many
SELECT id, tenant_id, name, type, capacity, floor, amenities, is_active, location, created_at FROM resources WHERE tenant_id = $1 AND type = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListResourcesByTypeParams struct {
	TenantID pgtype.UUID  `json:"tenant_id"`
	Type     ResourceType `json:"type"`
	Limit    int32        `json:"limit"`
	Offset   int32        `json:"offset"`
}

func (q *Queries) ListResourcesByType(ctx context.Context, arg ListResourcesByTypeParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByType,
		arg.TenantID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Capacity,
			&i.Floor,
			&i.Amenities,
			&i.IsActive,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSsoProviders = `-- name: ListSsoProviders :many
SELECT id, tenant_id, name, protocol, issuer_url, is_active, created_at FROM sso_providers WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSsoProvidersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListSsoProviders(ctx context.Context, arg ListSsoProvidersParams) ([]SsoProvider, error) {
	rows, err := q.db.Query(ctx, listSsoProviders, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoProvider
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Protocol,
			&i.IssuerUrl,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSsoProvidersActive = `-- name: ListSsoProvidersActive :many
SELECT id, tenant_id, name, protocol, issuer_url, is_active, created_at FROM sso_providers WHERE tenant_id = $1 AND is_active = TRUE ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSsoProvidersActiveParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListSsoProvidersActive(ctx context.Context, arg ListSsoProvidersActiveParams) ([]SsoProvider, error) {
	rows, err := q.db.Query(ctx, listSsoProvidersActive, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoProvider
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Protocol,
			&i.IssuerUrl,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, name, role, created_at FROM users WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservations SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, tenant_id, user_id, resource_id, during, status, notes, created_at, updated_at
`

type UpdateReservationStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status ReservationStatus `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.Status)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ResourceID,
		&i.During,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources SET name = $2, type = $3, capacity = $4, floor = $5, amenities = $6, is_active = $7, location = $8 WHERE id = $1 RETURNING id, tenant_id, name, type, capacity, floor, amenities, is_active, location, created_at
`

type UpdateResourceParams struct {
	ID        pgtype.UUID  `json:"id"`
	Name      string       `json:"name"`
	Type      ResourceType `json:"type"`
	Capacity  int32        `json:"capacity"`
	Floor     pgtype.Int4  `json:"floor"`
	Amenities []string     `json:"amenities"`
	IsActive  bool         `json:"is_active"`
	Location  interface{}  `json:"location"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Capacity,
		arg.Floor,
		arg.Amenities,
		arg.IsActive,
		arg.Location,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Capacity,
		&i.Floor,
		&i.Amenities,
		&i.IsActive,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, slug = $3, sso_enforced = $4 WHERE id = $1 RETURNING id, name, slug, sso_enforced, created_at
`

type UpdateTenantParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	SsoEnforced bool        `json:"sso_enforced"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.SsoEnforced,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SsoEnforced,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, role = $3 WHERE id = $1 RETURNING id, tenant_id, email, name, role, created_at
`

type UpdateUserParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Role UserRole    `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
